package com.codecool.spacer.model;

public enum Manufacturer {
    AEGIS_DYNAMICS, ANVIL_AEROSPACE, ARGO_ASTRONAUTICS, BANU, CRUSADER_INDUSTRIES, DRAKE_INTERPLANETARY,
    GREYCAT_INDUSTRIAL, TUMBRIL, VANDUUL
}
